import "./globals.css";
import { Inter, Tenali_Ramakrishna, Ubuntu_Condensed } from "next/font/google";

const inter = Inter({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-inter",
});
const ubuntu = Ubuntu_Condensed({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-ubuntu",
});
const tenali = Tenali_Ramakrishna({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-tenali",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const classNames = ` ${inter.variable} ${tenali.variable} ${ubuntu.variable} `;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames}>{children}</body>
    </html>
  );
}
